//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESjednica.WebUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLA
    {
        public int ID { get; set; }
    
        public virtual STAVKA_DNEVNOG_REDA STAVKA_DNEVNOG_REDA { get; set; }
        public virtual TIP_GLASA TIP_GLASA { get; set; }
        public virtual UCESNIK UCESNIK { get; set; }
    }
}
