//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESjednica.WebUI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbConnection : DbContext
    {
        public DbConnection()
            : base("name=DbConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHAT_PORUKA> CHAT_PORUKA { get; set; }
        public virtual DbSet<DNEVNI_RED> DNEVNI_RED { get; set; }
        public virtual DbSet<GLA> GLAS { get; set; }
        public virtual DbSet<PRILOG> PRILOGs { get; set; }
        public virtual DbSet<SJEDNICA> SJEDNICAs { get; set; }
        public virtual DbSet<STATUS_SJEDNICE> STATUS_SJEDNICE { get; set; }
        public virtual DbSet<STATUS_STAVKE_DNEVNOG_REDA> STATUS_STAVKE_DNEVNOG_REDA { get; set; }
        public virtual DbSet<STATUS_UCESNIKA> STATUS_UCESNIKA { get; set; }
        public virtual DbSet<STAVKA_DNEVNOG_REDA> STAVKA_DNEVNOG_REDA { get; set; }
        public virtual DbSet<TIP_GLASA> TIP_GLASA { get; set; }
        public virtual DbSet<TIP_UCESNIKA> TIP_UCESNIKA { get; set; }
        public virtual DbSet<UCESNIK> UCESNIKs { get; set; }
        public virtual DbSet<ZAPISNIK> ZAPISNIKs { get; set; }
    }
}
