//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESjednica.WebUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRILOG
    {
        public PRILOG()
        {
            this.ZAPISNIKs = new HashSet<ZAPISNIK>();
        }
    
        public int ID { get; set; }
        public string NAZIV { get; set; }
        public string CONTENT_TYPE { get; set; }
        public byte[] SADRZAJ { get; set; }
    
        public virtual ICollection<ZAPISNIK> ZAPISNIKs { get; set; }
    }
}
