//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESjednica.WebUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAVKA_DNEVNOG_REDA
    {
        public STAVKA_DNEVNOG_REDA()
        {
            this.GLAS = new HashSet<GLA>();
        }
    
        public int ID { get; set; }
        public decimal REDNI_BROJ { get; set; }
        public string NASLOV { get; set; }
        public string OPIS { get; set; }
    
        public virtual DNEVNI_RED DNEVNI_RED { get; set; }
        public virtual ICollection<GLA> GLAS { get; set; }
        public virtual STATUS_STAVKE_DNEVNOG_REDA STATUS_STAVKE_DNEVNOG_REDA { get; set; }
    }
}
