//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESjednica.WebUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIP_GLASA
    {
        public TIP_GLASA()
        {
            this.GLAS = new HashSet<GLA>();
        }
    
        public int ID { get; set; }
        public string NAZIV { get; set; }
    
        public virtual ICollection<GLA> GLAS { get; set; }
    }
}
