//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESjednica.WebUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZAPISNIK
    {
        public ZAPISNIK()
        {
            this.SJEDNICAs = new HashSet<SJEDNICA>();
        }
    
        public int ID { get; set; }
        public string TEKST { get; set; }
    
        public virtual PRILOG PRILOG { get; set; }
        public virtual ICollection<SJEDNICA> SJEDNICAs { get; set; }
        public virtual SJEDNICA SJEDNICA { get; set; }
        public virtual UCESNIK UCESNIK { get; set; }
    }
}
