//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESjedniceServis.DbModel
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class CHAT_PORUKA
    {
        public int ID { get; set; }
        public string PORUKA { get; set; }
        public System.DateTime VRIJEME { get; set; }
        [JsonIgnore]
        public virtual STAVKA_DNEVNOG_REDA STAVKA_DNEVNOG_REDA { get; set; }
        [JsonIgnore]
        public virtual UCESNIK UCESNIK { get; set; }
    }
}
