//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESjedniceServis.DbModel
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class PRILOG
    {
        public int ID { get; set; }
        public string NAZIV { get; set; }
        public string CONTENT_TYPE { get; set; }
        public byte[] SADRZAJ { get; set; }
      [JsonIgnore]
        public virtual SJEDNICA SJEDNICA { get; set; }
    }
}
