//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESjedniceServis.DbModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eSjedniceEntities : DbContext
    {
        public eSjedniceEntities()
            : base("name=eSjedniceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHAT_PORUKA> CHAT_PORUKA { get; set; }
        public virtual DbSet<CV_USER_INFO> CV_USER_INFO { get; set; }
        public virtual DbSet<GLAS> GLAS { get; set; }
        public virtual DbSet<PRILOG> PRILOG { get; set; }
        public virtual DbSet<SJEDNICA> SJEDNICA { get; set; }
        public virtual DbSet<STATUS_SJEDNICE> STATUS_SJEDNICE { get; set; }
        public virtual DbSet<STATUS_STAVKE_DNEVNOG_REDA> STATUS_STAVKE_DNEVNOG_REDA { get; set; }
        public virtual DbSet<STATUS_UCESNIKA> STATUS_UCESNIKA { get; set; }
        public virtual DbSet<STAVKA_DNEVNOG_REDA> STAVKA_DNEVNOG_REDA { get; set; }
        public virtual DbSet<TIP_GLASA> TIP_GLASA { get; set; }
        public virtual DbSet<TIP_UCESNIKA> TIP_UCESNIKA { get; set; }
        public virtual DbSet<UCESNIK> UCESNIK { get; set; }
    }
}
