//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESjedniceServis.DbModel
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class STATUS_UCESNIKA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STATUS_UCESNIKA()
        {
            this.UCESNIK = new HashSet<UCESNIK>();
        }
    
        public int ID { get; set; }
        public string NAZIV { get; set; }
    [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UCESNIK> UCESNIK { get; set; }
    }
}
